# Generated by Django 5.1.2 on 2025-08-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Views',
            new_name='PageViews',
        ),
    ]
