# Generated by Django 5.1.2 on 2025-08-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rename_views_pageviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
